// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxyKH0RZ7gjks96Z8OTYE-6ZL1sP7eLuc',
    appId: '1:1075115154014:web:b66de231245f4c130132cf',
    messagingSenderId: '1075115154014',
    projectId: 'muj-carpool-app',
    authDomain: 'muj-carpool-app.firebaseapp.com',
    storageBucket: 'muj-carpool-app.appspot.com',
    measurementId: 'G-BQRFVKTQ73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPDU1hQEvBb31HHNoTKCdjLgS1oZ_Zbko',
    appId: '1:1075115154014:android:8710f1abf8cb280f0132cf',
    messagingSenderId: '1075115154014',
    projectId: 'muj-carpool-app',
    storageBucket: 'muj-carpool-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyP80tSMw_6f45DFK24WZ_GQa_IkAXyJA',
    appId: '1:1075115154014:ios:06140c300173f7a60132cf',
    messagingSenderId: '1075115154014',
    projectId: 'muj-carpool-app',
    storageBucket: 'muj-carpool-app.appspot.com',
    iosClientId: '1075115154014-1tdq4gt2lke3nukq4ic010pcj3h6eh3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyP80tSMw_6f45DFK24WZ_GQa_IkAXyJA',
    appId: '1:1075115154014:ios:06140c300173f7a60132cf',
    messagingSenderId: '1075115154014',
    projectId: 'muj-carpool-app',
    storageBucket: 'muj-carpool-app.appspot.com',
    iosClientId: '1075115154014-1tdq4gt2lke3nukq4ic010pcj3h6eh3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiApp',
  );
}
